name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Action
        run: echo "::error file=Project/Sources/Methods/kobuild.4dm,line=4::Something went wrong"
      
